package crud

const pathHome = "home"
const pathEntityCreateAjax = "entity-create-ajax"
const pathEntityCreateModal = "entity-create-modal"
const pathEntityManager = "entity-manager"
const pathEntityRead = "entity-read"
const pathEntityUpdate = "entity-update"
const pathEntityUpdateAjax = "entity-update-ajax"
const pathEntityTrashAjax = "entity-trash-ajax"

const FORM_FIELD_TYPE_BLOCKAREA = "blockarea"
const FORM_FIELD_TYPE_BLOCKEDITOR = "blockeditor"
const FORM_FIELD_TYPE_CHECKBOX = "checkbox"
const FORM_FIELD_TYPE_COLOR = "color"
const FORM_FIELD_TYPE_DATE = "date"
const FORM_FIELD_TYPE_DATETIME = "datetime"
const FORM_FIELD_TYPE_EMAIL = "email"
const FORM_FIELD_TYPE_FILE = "file"
const FORM_FIELD_TYPE_HIDDEN = "hidden"
const FORM_FIELD_TYPE_HTMLAREA = "htmlarea"
const FORM_FIELD_TYPE_IMAGE = "image"
const FORM_FIELD_TYPE_IMAGE_INLINE = "image_inline"
const FORM_FIELD_TYPE_NUMBER = "number"
const FORM_FIELD_TYPE_PASSWORD = "password"
const FORM_FIELD_TYPE_RADIO = "radio"
const FORM_FIELD_TYPE_RAW = "raw"
const FORM_FIELD_TYPE_REPEATER = "repeater"
const FORM_FIELD_TYPE_SELECT = "select"
const FORM_FIELD_TYPE_STRING = "string"
const FORM_FIELD_TYPE_TABLE = "table"
const FORM_FIELD_TYPE_TEL = "tel"
const FORM_FIELD_TYPE_TEXTAREA = "textarea"
const FORM_FIELD_TYPE_URL = "url"
